extern crate pwasm_std;

use pwasm_std::{Vec, String};

pub fn convert(input_string_vector: Vec<i64>) -> String {
	let mut string_to_return = String::from("");
	for int in input_string_vector.iter() {
        match int {
            &40 => string_to_return = string_to_return + "(",
            &41 => string_to_return = string_to_return + ")",
			&48 => string_to_return = string_to_return + "0",
			&49 => string_to_return = string_to_return + "1",
			&50 => string_to_return = string_to_return + "2",
			&51 => string_to_return = string_to_return + "3",
			&52 => string_to_return = string_to_return + "4",
			&53 => string_to_return = string_to_return + "5",
			&54 => string_to_return = string_to_return + "6",
			&55 => string_to_return = string_to_return + "7",
			&56 => string_to_return = string_to_return + "8",
			&57 => string_to_return = string_to_return + "9",
			&65 => string_to_return = string_to_return + "A",
			&66 => string_to_return = string_to_return + "B",
			&67 => string_to_return = string_to_return + "C",
			&68 => string_to_return = string_to_return + "D",
			&69 => string_to_return = string_to_return + "E",
			&70 => string_to_return = string_to_return + "F",
			&71 => string_to_return = string_to_return + "G",
			&72 => string_to_return = string_to_return + "H",
			&73 => string_to_return = string_to_return + "I",
			&74 => string_to_return = string_to_return + "J",
			&75 => string_to_return = string_to_return + "K",
			&76 => string_to_return = string_to_return + "L",
			&77 => string_to_return = string_to_return + "M",
			&78 => string_to_return = string_to_return + "N",
			&79 => string_to_return = string_to_return + "O",
			&80 => string_to_return = string_to_return + "P",
			&81 => string_to_return = string_to_return + "Q",
			&82 => string_to_return = string_to_return + "R",
			&83 => string_to_return = string_to_return + "S",
			&84 => string_to_return = string_to_return + "T",
			&85 => string_to_return = string_to_return + "U",
			&86 => string_to_return = string_to_return + "V",
			&87 => string_to_return = string_to_return + "W",
			&88 => string_to_return = string_to_return + "X",
			&89 => string_to_return = string_to_return + "Y",
			&90 => string_to_return = string_to_return + "Z",
			&97 => string_to_return = string_to_return + "a",
			&98 => string_to_return = string_to_return + "b",
			&99 => string_to_return = string_to_return + "c",
			&100 => string_to_return = string_to_return + "d",
			&101 => string_to_return = string_to_return + "e",
			&102 => string_to_return = string_to_return + "f",
			&103 => string_to_return = string_to_return + "g",
			&104 => string_to_return = string_to_return + "h",
			&105 => string_to_return = string_to_return + "i",
			&106 => string_to_return = string_to_return + "j",
			&107 => string_to_return = string_to_return + "k",
			&108 => string_to_return = string_to_return + "l",
			&109 => string_to_return = string_to_return + "m",
			&110 => string_to_return = string_to_return + "n",
			&111 => string_to_return = string_to_return + "o",
			&112 => string_to_return = string_to_return + "p",
			&113 => string_to_return = string_to_return + "q",
			&114 => string_to_return = string_to_return + "r",
			&115 => string_to_return = string_to_return + "s",
			&116 => string_to_return = string_to_return + "t",
			&117 => string_to_return = string_to_return + "u",
			&118 => string_to_return = string_to_return + "v",
			&119 => string_to_return = string_to_return + "w",
			&120 => string_to_return = string_to_return + "x",
			&121 => string_to_return = string_to_return + "y",
			&122 => string_to_return = string_to_return + "z",
			_ => string_to_return = string_to_return + "",
        }
    }
	string_to_return
}
